/**
 * Popular sites, so the command bar can suggest (and complete) them before they're in your history:
 * "yout" → youtube.com. Hand-picked from the most visited sites people go to on purpose: one address
 * per service (no youtu.be, t.co or country copies), no infrastructure domains (CDNs, APIs, ad
 * servers), nothing adult. Most popular first, which is the order matches are offered in. A name can
 * carry other words people type for the site ("X (Twitter)").
 */
const SITES: [domain: string, name: string][] = [
  ['google.com', 'Google'],
  ['youtube.com', 'YouTube'],
  ['facebook.com', 'Facebook'],
  ['instagram.com', 'Instagram'],
  ['wikipedia.org', 'Wikipedia'],
  ['x.com', 'X (Twitter)'],
  ['reddit.com', 'Reddit'],
  ['amazon.com', 'Amazon'],
  ['chatgpt.com', 'ChatGPT'],
  ['whatsapp.com', 'WhatsApp'],
  ['web.whatsapp.com', 'WhatsApp Web'],
  ['mail.google.com', 'Gmail'],
  ['linkedin.com', 'LinkedIn'],
  ['netflix.com', 'Netflix'],
  ['tiktok.com', 'TikTok'],
  ['bing.com', 'Bing'],
  ['yahoo.com', 'Yahoo'],
  ['github.com', 'GitHub'],
  ['microsoft.com', 'Microsoft'],
  ['apple.com', 'Apple'],
  ['outlook.live.com', 'Outlook'],
  ['office.com', 'Microsoft 365 (Office)'],
  ['twitch.tv', 'Twitch'],
  ['pinterest.com', 'Pinterest'],
  ['claude.ai', 'Claude'],
  ['gemini.google.com', 'Gemini'],
  ['duckduckgo.com', 'DuckDuckGo'],
  ['ebay.com', 'eBay'],
  ['discord.com', 'Discord'],
  ['spotify.com', 'Spotify'],
  ['open.spotify.com', 'Spotify Web Player'],
  ['drive.google.com', 'Google Drive'],
  ['docs.google.com', 'Google Docs'],
  ['maps.google.com', 'Google Maps'],
  ['translate.google.com', 'Google Translate'],
  ['calendar.google.com', 'Google Calendar'],
  ['meet.google.com', 'Google Meet'],
  ['photos.google.com', 'Google Photos'],
  ['news.google.com', 'Google News'],
  ['scholar.google.com', 'Google Scholar'],
  ['zoom.us', 'Zoom'],
  ['stackoverflow.com', 'Stack Overflow'],
  ['quora.com', 'Quora'],
  ['imdb.com', 'IMDb'],
  ['paypal.com', 'PayPal'],
  ['walmart.com', 'Walmart'],
  ['cnn.com', 'CNN'],
  ['bbc.com', 'BBC'],
  ['nytimes.com', 'The New York Times'],
  ['espn.com', 'ESPN'],
  ['weather.com', 'The Weather Channel'],
  ['booking.com', 'Booking.com'],
  ['airbnb.com', 'Airbnb'],
  ['canva.com', 'Canva'],
  ['figma.com', 'Figma'],
  ['notion.so', 'Notion'],
  ['dropbox.com', 'Dropbox'],
  ['icloud.com', 'iCloud'],
  ['perplexity.ai', 'Perplexity'],
  ['copilot.microsoft.com', 'Copilot'],
  ['telegram.org', 'Telegram'],
  ['web.telegram.org', 'Telegram Web'],
  ['snapchat.com', 'Snapchat'],
  ['threads.com', 'Threads'],
  ['bsky.app', 'Bluesky'],
  ['tumblr.com', 'Tumblr'],
  ['messenger.com', 'Messenger'],
  ['primevideo.com', 'Prime Video'],
  ['disneyplus.com', 'Disney+ (Disney Plus)'],
  ['hulu.com', 'Hulu'],
  ['max.com', 'Max (HBO)'],
  ['tv.apple.com', 'Apple TV'],
  ['music.apple.com', 'Apple Music'],
  ['music.youtube.com', 'YouTube Music'],
  ['soundcloud.com', 'SoundCloud'],
  ['vimeo.com', 'Vimeo'],
  ['crunchyroll.com', 'Crunchyroll'],
  ['paramountplus.com', 'Paramount+ (Paramount Plus)'],
  ['peacocktv.com', 'Peacock'],
  ['dailymotion.com', 'Dailymotion'],
  ['kick.com', 'Kick'],
  ['rumble.com', 'Rumble'],
  ['bilibili.com', 'Bilibili'],
  ['etsy.com', 'Etsy'],
  ['aliexpress.com', 'AliExpress'],
  ['temu.com', 'Temu'],
  ['shein.com', 'Shein'],
  ['target.com', 'Target'],
  ['bestbuy.com', 'Best Buy'],
  ['costco.com', 'Costco'],
  ['homedepot.com', 'The Home Depot'],
  ['lowes.com', 'Lowe’s'],
  ['ikea.com', 'IKEA'],
  ['wayfair.com', 'Wayfair'],
  ['macys.com', 'Macy’s'],
  ['nike.com', 'Nike'],
  ['zara.com', 'Zara'],
  ['samsung.com', 'Samsung'],
  ['newegg.com', 'Newegg'],
  ['craigslist.org', 'Craigslist'],
  ['alibaba.com', 'Alibaba'],
  ['flipkart.com', 'Flipkart'],
  ['shopify.com', 'Shopify'],
  ['instacart.com', 'Instacart'],
  ['doordash.com', 'DoorDash'],
  ['ubereats.com', 'Uber Eats'],
  ['grubhub.com', 'Grubhub'],
  ['uber.com', 'Uber'],
  ['lyft.com', 'Lyft'],
  ['expedia.com', 'Expedia'],
  ['tripadvisor.com', 'Tripadvisor'],
  ['kayak.com', 'Kayak'],
  ['skyscanner.net', 'Skyscanner'],
  ['hotels.com', 'Hotels.com'],
  ['agoda.com', 'Agoda'],
  ['trip.com', 'Trip.com'],
  ['yelp.com', 'Yelp'],
  ['opentable.com', 'OpenTable'],
  ['allrecipes.com', 'Allrecipes'],
  ['zillow.com', 'Zillow'],
  ['realtor.com', 'Realtor.com'],
  ['redfin.com', 'Redfin'],
  ['indeed.com', 'Indeed'],
  ['glassdoor.com', 'Glassdoor'],
  ['upwork.com', 'Upwork'],
  ['fiverr.com', 'Fiverr'],
  ['theguardian.com', 'The Guardian'],
  ['washingtonpost.com', 'The Washington Post'],
  ['foxnews.com', 'Fox News'],
  ['reuters.com', 'Reuters'],
  ['apnews.com', 'AP News'],
  ['bloomberg.com', 'Bloomberg'],
  ['wsj.com', 'The Wall Street Journal'],
  ['forbes.com', 'Forbes'],
  ['cnbc.com', 'CNBC'],
  ['nbcnews.com', 'NBC News'],
  ['aljazeera.com', 'Al Jazeera'],
  ['usatoday.com', 'USA Today'],
  ['npr.org', 'NPR'],
  ['businessinsider.com', 'Business Insider'],
  ['theverge.com', 'The Verge'],
  ['techcrunch.com', 'TechCrunch'],
  ['wired.com', 'Wired'],
  ['arstechnica.com', 'Ars Technica'],
  ['engadget.com', 'Engadget'],
  ['huffpost.com', 'HuffPost'],
  ['dailymail.co.uk', 'Daily Mail'],
  ['independent.co.uk', 'The Independent'],
  ['bbc.co.uk', 'BBC UK'],
  ['time.com', 'Time'],
  ['economist.com', 'The Economist'],
  ['ft.com', 'Financial Times'],
  ['axios.com', 'Axios'],
  ['politico.com', 'Politico'],
  ['theatlantic.com', 'The Atlantic'],
  ['newyorker.com', 'The New Yorker'],
  ['vox.com', 'Vox'],
  ['buzzfeed.com', 'BuzzFeed'],
  ['finance.yahoo.com', 'Yahoo Finance'],
  ['marketwatch.com', 'MarketWatch'],
  ['investing.com', 'Investing.com'],
  ['tradingview.com', 'TradingView'],
  ['medium.com', 'Medium'],
  ['substack.com', 'Substack'],
  ['news.ycombinator.com', 'Hacker News'],
  ['producthunt.com', 'Product Hunt'],
  ['wiktionary.org', 'Wiktionary'],
  ['britannica.com', 'Britannica'],
  ['merriam-webster.com', 'Merriam-Webster'],
  ['dictionary.com', 'Dictionary.com'],
  ['thesaurus.com', 'Thesaurus.com'],
  ['archive.org', 'Internet Archive'],
  ['coursera.org', 'Coursera'],
  ['udemy.com', 'Udemy'],
  ['khanacademy.org', 'Khan Academy'],
  ['duolingo.com', 'Duolingo'],
  ['edx.org', 'edX'],
  ['quizlet.com', 'Quizlet'],
  ['chegg.com', 'Chegg'],
  ['wolframalpha.com', 'Wolfram Alpha'],
  ['goodreads.com', 'Goodreads'],
  ['rottentomatoes.com', 'Rotten Tomatoes'],
  ['letterboxd.com', 'Letterboxd'],
  ['genius.com', 'Genius'],
  ['fandom.com', 'Fandom'],
  ['deepl.com', 'DeepL Translate'],
  ['speedtest.net', 'Speedtest'],
  ['accuweather.com', 'AccuWeather'],
  ['timeanddate.com', 'Time and Date'],
  ['pandora.com', 'Pandora'],
  ['bandcamp.com', 'Bandcamp'],
  ['deezer.com', 'Deezer'],
  ['tidal.com', 'Tidal'],
  ['audible.com', 'Audible'],
  ['last.fm', 'Last.fm'],
  ['chase.com', 'Chase'],
  ['bankofamerica.com', 'Bank of America'],
  ['wellsfargo.com', 'Wells Fargo'],
  ['capitalone.com', 'Capital One'],
  ['americanexpress.com', 'American Express (Amex)'],
  ['citi.com', 'Citi'],
  ['fidelity.com', 'Fidelity'],
  ['schwab.com', 'Charles Schwab'],
  ['vanguard.com', 'Vanguard'],
  ['robinhood.com', 'Robinhood'],
  ['coinbase.com', 'Coinbase'],
  ['binance.com', 'Binance'],
  ['venmo.com', 'Venmo'],
  ['wise.com', 'Wise'],
  ['revolut.com', 'Revolut'],
  ['stripe.com', 'Stripe'],
  ['store.steampowered.com', 'Steam'],
  ['roblox.com', 'Roblox'],
  ['epicgames.com', 'Epic Games'],
  ['xbox.com', 'Xbox'],
  ['playstation.com', 'PlayStation'],
  ['nintendo.com', 'Nintendo'],
  ['minecraft.net', 'Minecraft'],
  ['ea.com', 'EA'],
  ['ign.com', 'IGN'],
  ['gamespot.com', 'GameSpot'],
  ['chess.com', 'Chess.com'],
  ['lichess.org', 'Lichess'],
  ['itch.io', 'itch.io'],
  ['gitlab.com', 'GitLab'],
  ['developer.mozilla.org', 'MDN Web Docs'],
  ['npmjs.com', 'npm'],
  ['pypi.org', 'PyPI'],
  ['hub.docker.com', 'Docker Hub'],
  ['developer.apple.com', 'Apple Developer'],
  ['vercel.com', 'Vercel'],
  ['netlify.com', 'Netlify'],
  ['cloudflare.com', 'Cloudflare'],
  ['aws.amazon.com', 'AWS (Amazon Web Services)'],
  ['console.cloud.google.com', 'Google Cloud Console'],
  ['portal.azure.com', 'Azure Portal'],
  ['digitalocean.com', 'DigitalOcean'],
  ['heroku.com', 'Heroku'],
  ['supabase.com', 'Supabase'],
  ['firebase.google.com', 'Firebase'],
  ['render.com', 'Render'],
  ['codepen.io', 'CodePen'],
  ['codesandbox.io', 'CodeSandbox'],
  ['replit.com', 'Replit'],
  ['leetcode.com', 'LeetCode'],
  ['kaggle.com', 'Kaggle'],
  ['huggingface.co', 'Hugging Face'],
  ['w3schools.com', 'W3Schools'],
  ['freecodecamp.org', 'freeCodeCamp'],
  ['geeksforgeeks.org', 'GeeksforGeeks'],
  ['dev.to', 'DEV Community'],
  ['linear.app', 'Linear'],
  ['slack.com', 'Slack'],
  ['app.slack.com', 'Slack (web app)'],
  ['teams.microsoft.com', 'Microsoft Teams'],
  ['onedrive.live.com', 'OneDrive'],
  ['trello.com', 'Trello'],
  ['asana.com', 'Asana'],
  ['monday.com', 'monday.com'],
  ['clickup.com', 'ClickUp'],
  ['airtable.com', 'Airtable'],
  ['miro.com', 'Miro'],
  ['evernote.com', 'Evernote'],
  ['todoist.com', 'Todoist'],
  ['calendly.com', 'Calendly'],
  ['docusign.com', 'DocuSign'],
  ['grammarly.com', 'Grammarly'],
  ['box.com', 'Box'],
  ['proton.me', 'Proton (Proton Mail)'],
  ['character.ai', 'Character.AI'],
  ['poe.com', 'Poe'],
  ['grok.com', 'Grok'],
  ['chat.deepseek.com', 'DeepSeek'],
  ['chat.mistral.ai', 'Le Chat (Mistral)'],
  ['midjourney.com', 'Midjourney'],
  ['adobe.com', 'Adobe'],
  ['dell.com', 'Dell'],
  ['hp.com', 'HP'],
  ['verizon.com', 'Verizon'],
  ['att.com', 'AT&T'],
  ['t-mobile.com', 'T-Mobile'],
  ['xfinity.com', 'Xfinity'],
  ['usps.com', 'USPS'],
  ['ups.com', 'UPS'],
  ['fedex.com', 'FedEx'],
  ['dhl.com', 'DHL'],
  ['godaddy.com', 'GoDaddy'],
  ['namecheap.com', 'Namecheap'],
  ['squarespace.com', 'Squarespace'],
  ['wix.com', 'Wix'],
  ['wordpress.com', 'WordPress'],
  ['patreon.com', 'Patreon'],
  ['kickstarter.com', 'Kickstarter'],
  ['gofundme.com', 'GoFundMe'],
  ['eventbrite.com', 'Eventbrite'],
  ['ticketmaster.com', 'Ticketmaster'],
  ['stubhub.com', 'StubHub'],
  ['1password.com', '1Password'],
  ['bitwarden.com', 'Bitwarden'],
  ['nordvpn.com', 'NordVPN'],
  ['downdetector.com', 'Downdetector'],
  ['virustotal.com', 'VirusTotal'],
  ['imgur.com', 'Imgur'],
  ['giphy.com', 'GIPHY'],
  ['unsplash.com', 'Unsplash'],
  ['pexels.com', 'Pexels'],
  ['dribbble.com', 'Dribbble'],
  ['behance.net', 'Behance'],
  ['deviantart.com', 'DeviantArt'],
  ['flickr.com', 'Flickr'],
  ['artstation.com', 'ArtStation'],
  ['vk.com', 'VK'],
  ['weibo.com', 'Weibo'],
  ['mastodon.social', 'Mastodon'],
  ['nextdoor.com', 'Nextdoor'],
  ['baidu.com', 'Baidu'],
  ['yandex.ru', 'Yandex'],
  ['naver.com', 'Naver'],
  ['daum.net', 'Daum'],
  ['yahoo.co.jp', 'Yahoo! Japan'],
  ['rakuten.co.jp', 'Rakuten'],
  ['qq.com', 'QQ'],
  ['taobao.com', 'Taobao'],
  ['jd.com', 'JD.com'],
  ['mail.ru', 'Mail.ru'],
  ['ok.ru', 'Odnoklassniki (OK)'],
  ['avito.ru', 'Avito'],
  ['globo.com', 'Globo'],
  ['uol.com.br', 'UOL'],
  ['zomato.com', 'Zomato'],
  ['swiggy.com', 'Swiggy'],
  ['paytm.com', 'Paytm'],
  ['ecosia.org', 'Ecosia'],
  ['startpage.com', 'Startpage'],
  ['search.brave.com', 'Brave Search']
]

export interface PopularSite {
  domain: string
  name: string
}

const POPULAR: PopularSite[] = SITES.map(([domain, name]) => ({ domain, name }))
const words = new Map(
  POPULAR.map((site) => [
    site,
    site.name
      .toLowerCase()
      .split(/[^a-z0-9+]+/)
      .filter(Boolean)
  ])
)

/** What was typed, as an address start ("https://www.you" → "you"); null for phrases and paths. */
function prefix(query: string): string | null {
  const q = query
    .trim()
    .toLowerCase()
    .replace(/^https?:\/\//, '')
    .replace(/^www\./, '')
  return q.length >= 2 && !/[\s/]/.test(q) ? q : null
}

/** The most popular site whose address starts with what you typed (for completing it in the field). */
export function popularByAddress(query: string): PopularSite | undefined {
  const q = prefix(query)
  return q ? POPULAR.find((site) => site.domain.startsWith(q)) : undefined
}

/** Popular sites whose address or name begins with what you typed, most popular first. */
export function popularMatches(query: string, limit: number): PopularSite[] {
  const q = prefix(query)
  if (!q) return []
  const found: PopularSite[] = []
  for (const site of POPULAR) {
    if (site.domain.startsWith(q) || site.name.toLowerCase().startsWith(q) || words.get(site)!.some((w) => w.startsWith(q))) {
      found.push(site)
      if (found.length >= limit) break
    }
  }
  return found
}
